"""
Job status and file download endpoints.
Path traversal protection uses safe_path_check from security module.
"""
import os
from pathlib import Path
from typing import Optional
import logging

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

from ..core.storage import get_job
from ..core.config import OUTPUT_DIR
from ..core.security import safe_path_check, sanitize_filename

router = APIRouter(prefix="/api", tags=["status"])
log = logging.getLogger(__name__)

# Whitelist of valid file_type values to prevent injection
VALID_FILE_TYPES = frozenset({
    "cleaned", "merged", "review", "report", "backup", "master", "result",
    "transformed", "mapping_report", "compliance_report",
    "migration_log", "receipt", "summary", "checked",
})

XLSX_MIME = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"


@router.get("/status/{job_id}")
async def get_status(job_id: str):
    """Poll job status (single, bulk, or quick engine)."""
    job = get_job(job_id)
    if not job:
        raise HTTPException(404, "Job not found")
    return job


@router.get("/download/{job_id}/{file_type}")
async def download_file(
    job_id: str,
    file_type: str,
    file: Optional[str] = None,
):
    """
    Download a processed file.

    file_type: 'cleaned' | 'merged' | 'review' | 'report' | 'backup' | 'master' | 'result'
    For bulk jobs add ?file=filename.xlsx to select which input file's output.
    """
    # Alias the new frontend UI keys to the actual outputs generated by production.py
    file_map = {
        "transformed": "cleaned",
        "mapping_report": "report",
        "compliance_report": "review",
        "migration_log": "report",
        "receipt": "cleaned",
        "summary": "master",
    }
    actual_file_type = file_map.get(file_type, file_type)

    if actual_file_type not in VALID_FILE_TYPES:
        raise HTTPException(
            400,
            f"Invalid file_type '{file_type}'. Valid: {sorted(VALID_FILE_TYPES)}",
        )

    job = get_job(job_id)
    if not job:
        raise HTTPException(404, "Job not found")

    if "complete" not in job.get("status", ""):
        raise HTTPException(400, f"Job is '{job['status']}' — not ready yet")

    # Master report (bulk)
    if actual_file_type == "master":
        path = job.get("master_report", "")
        if not path or not os.path.exists(path):
            raise HTTPException(404, "Master report not found")
        safe_path_check(OUTPUT_DIR, path)
        return FileResponse(
            path=path,
            filename=f"MASTER_SUMMARY_{job_id}.xlsx",
            media_type=XLSX_MIME,
        )

    # Single-file job
    if job.get("type") != "bulk":
        path = (job.get("output_paths") or {}).get(actual_file_type, "")
        if not path or not os.path.exists(path):
            # Fallback if mapped file doesn't exist
            if actual_file_type == "report" and "master" in (job.get("output_paths") or {}):
                path = job["output_paths"]["master"]
            else:
                raise HTTPException(404, f"'{file_type}' file not found")
        safe_path_check(OUTPUT_DIR, path)
        return FileResponse(
            path=path,
            filename=os.path.basename(path),
            media_type=XLSX_MIME,
        )

    # Bulk job — pick by filename
    file_results = job.get("file_results", [])
    if not file_results:
        raise HTTPException(404, "No file results in this job")

    if file:
        safe_file = sanitize_filename(file)
        record = next((r for r in file_results if r.get("file") == safe_file), None)
        if not record:
            record = next((r for r in file_results if r.get("file") == file), None)
        if not record:
            raise HTTPException(
                404,
                f"'{file}' not in job. "
                f"Available: {[r['file'] for r in file_results]}",
            )
    else:
        if len(file_results) > 1:
            raise HTTPException(
                400,
                f"Bulk job has {len(file_results)} files — add ?file=<name>. "
                f"Available: {[r['file'] for r in file_results]}",
            )
        record = file_results[0]

    path = (record.get("output_paths") or {}).get(actual_file_type, "")
    if not path or not os.path.exists(path):
        raise HTTPException(404, f"'{file_type}' file not on disk")
    safe_path_check(OUTPUT_DIR, path)

    return FileResponse(
        path=path,
        filename=os.path.basename(path),
        media_type=XLSX_MIME,
    )